import * as m from '@/paraglide/messages.js';
import type { Outcome } from './rule-error';

// An error says three things (docs/product/voix.md): what happened, why, what to do. One sentence
// per code a rule can raise; an unknown code falls back to the generic sentence.
const sentences: Record<string, () => string> = {
  not_allowed: m.error_not_allowed,
  invalid_input: m.error_invalid_input,
  not_found: m.error_not_found,
  already_set_up: m.error_already_set_up,
  not_set_up: m.error_not_set_up,
  already_clocked_in: m.error_already_clocked_in,
  not_clocked_in: m.error_not_clocked_in,
  invoice_one_customer: m.error_invoice_one_customer,
  already_invoiced: m.error_already_invoiced,
  already_credited: m.error_already_credited,
  credit_note_not_credited: m.error_credit_note_final,
  credit_note_not_cashed: m.error_credit_note_final,
  paid_to_needs_wages: m.error_paid_to_needs_wages,
  statement_no_destination: m.error_statement_no_destination,
  site_code_taken: m.error_site_code_taken,
  site_plant_not_needed: m.error_site_plant_not_needed,
  site_plant_unknown: m.error_site_plant_unknown,
  site_last_counter: m.error_site_last_counter,
  site_plant_in_use: m.error_site_plant_in_use,
  owner_keeps_everything: m.error_owner_keeps_everything,
  permission_unknown: m.error_invalid_input,
  route_not_for_this_nature: m.error_route_not_for_this_nature,
  route_step_unknown: m.error_route_step_unknown,
  route_step_twice: m.error_route_step_twice,
  step_on_a_route: m.error_step_on_a_route,
  service_pricing_in_use: m.error_service_pricing_in_use,
  price_needs_article: m.error_invalid_input,
  price_per_kilo_has_no_article: m.error_invalid_input,
  pack_service_unknown: m.error_not_found,
  pack_service_wrong_mode: m.error_pack_service_wrong_mode,
  quantity_invalid: m.error_quantity_invalid,
  price_invalid: m.error_amount,
  amount_invalid: m.error_amount,
  not_sold: m.error_not_sold,
  discount_needs_reason: m.error_discount_needs_reason,
  discount_above_ceiling: m.error_discount_above_ceiling,
  order_not_open: m.error_order_not_open,
  order_not_ready: m.error_order_not_ready,
  reason_needed: m.error_reason_needed,
  refund_first: m.error_refund_first,
  order_cancelled: m.error_order_cancelled,
  payment_above_balance: m.error_payment_above_balance,
  refund_above_paid: m.error_refund_above_paid,
  phone_invalid: m.error_phone_invalid,
  phone_taken: m.error_phone_taken,
  customer_name_needed: m.error_customer_name_needed,
  customer_needed: m.error_customer_needed,
  site_does_not_receive: m.error_site_does_not_receive,
  not_your_site: m.error_not_your_site,
  cash_session_needed: m.error_cash_session_needed,
  cash_session_open: m.error_cash_session_open,
  cash_session_closed: m.error_cash_session_closed,
  not_your_till: m.error_not_your_till,
  site_needed: m.error_site_needed,
  recurring_not_from_till: m.error_recurring_not_from_till,
  expense_voided: m.error_expense_voided,
  expense_not_recurring: m.error_invalid_input,
  stop_before_start: m.error_stop_before_start,
  workshop_not_finished: m.error_workshop_not_finished,
  template_empty: m.error_template_empty,
  template_unknown_placeholder: m.error_template_unknown_placeholder,
  reminder_not_enabled: m.error_reminder_not_enabled,
  site_has_no_plant: m.error_site_has_no_plant,
  unit_finished: m.error_unit_finished,
  step_not_on_route: m.error_step_not_on_route,
  step_not_before: m.error_step_not_on_route,
  shift_invalid: m.error_shift_invalid,
  already_decided: m.error_already_decided,
  no_storage_fee: m.error_no_storage_fee,
  already_noticed: m.error_already_noticed,
  release_too_early: m.error_release_too_early,
  code_invalid: m.error_code_invalid,
  code_too_simple: m.error_code_too_simple,
  code_wrong: m.error_code_wrong,
  code_locked: m.error_code_locked,
  quick_switch_off: m.error_quick_switch_off,
  credit_below_cashed: m.error_credit_below_cashed,
  credit_insufficient: m.error_credit_insufficient,
  subscription_not_running: m.error_subscription_not_running,
  subscription_already_cashed: m.error_subscription_already_cashed,
  quote_expired: m.error_quote_expired,
};

/** The sentence a screen shows for a gesture that did not go through. */
export function errorSentence(code: string): string {
  return (sentences[code] ?? m.error_generic)();
}

/** The sentence of a failed outcome, or null when it went through. */
export function failure(outcome: Outcome<unknown>): string | null {
  return outcome.ok ? null : errorSentence(outcome.code);
}
