import { index, layout, rootRoute, route } from '@tanstack/virtual-file-routes';

// Every address of the app, once: files are named in English, addresses read in French (doctrine
// ARCHITECTURE_APP §3). A screen is a file of src/routes; an endpoint too, with server handlers.
export const routes = rootRoute('__root.tsx', [
  index('index.tsx'),
  // The signed-in screens share one frame: the shell, filtered by the person's rights.
  layout('app.tsx', [
    route('/demarrage', 'start.tsx'),
    route('/aujourdhui', 'today.tsx'),
    route('/depots', 'orders/index.tsx'),
    route('/depots/nouveau', 'orders/new.tsx'),
    route('/depots/$orderId', 'orders/$orderId.tsx'),
    route('/factures', 'invoices/index.tsx'),
    route('/devis', 'quotes/index.tsx'),
    route('/clients', 'customers/index.tsx'),
    route('/clients/$customerId', 'customers/$customerId.tsx'),
    route('/atelier', 'workshop/queue.tsx'),
    route('/livraisons', 'delivery/board.tsx'),
    route('/demander', 'assistant/ask.tsx'),
    route('/argent/caisse', 'money/till.tsx'),
    route('/argent/depenses', 'money/expenses.tsx'),
    route('/argent/resultat', 'money/result.tsx'),
    route('/argent/couts', 'money/costs.tsx'),
    route('/pressing/schema', 'business/diagram.tsx'),
    route('/pressing/catalogue', 'business/catalog.tsx'),
    route('/pressing/points', 'business/sites.tsx'),
    route('/pressing/reseau', 'business/network.tsx'),
    route('/pressing/stock', 'business/stock.tsx'),
    route('/pressing/equipe', 'business/team.tsx'),
    route('/pressing/travail', 'business/work.tsx'),
    route('/pressing/gerant', 'business/manager.tsx'),
    route('/pressing/messages', 'business/messages.tsx'),
    route('/pressing/releve', 'business/statement.tsx'),
    route('/pressing/reglages', 'business/settings.tsx'),
    route('/verification/$draftId', 'review/$draftId.tsx'),
    route('/journal', 'journal.tsx'),
    route('/aide', 'help.tsx'),
  ]),
  // The receipt stands outside the frame: only the ticket goes to the printer.
  route('/depots/$orderId/recu', 'orders/receipt.tsx'),
  // An invoice too: only the document goes to the printer.
  route('/factures/$invoiceId', 'invoices/$invoiceId.tsx'),
  route('/devis/$quoteId', 'quotes/$quoteId.tsx'),
  // A slip too: the courier carries it, the customer signs it.
  route('/livraisons/$deliveryId', 'delivery/slip.tsx'),
  route('/transferts/$transferId', 'business/transfer-slip.tsx'),
  // Public pages: read without signing in.
  route('/mentions-legales', 'legal/notice.tsx'),
  route('/confidentialite', 'legal/privacy.tsx'),
  route('/conditions', 'legal/terms.tsx'),
  route('/auth/connexion', 'auth/sign-in.ts'),
  route('/auth/callback', 'auth/callback.ts'),
  route('/auth/sortie', 'auth/sign-out.ts'),
  route('/auth/personne', 'auth/person.ts'),
  route('/webhooks/whatsapp', 'webhooks/whatsapp.ts'),
  route('/webhooks/telegram', 'webhooks/telegram.ts'),
  route('/mcp', 'api/mcp.ts'),
  route('/api/v1/$', 'api/v1.ts'),
  route('/api/avis', 'api/feedback.ts'),
  route('/api/assistant', 'api/assistant.ts'),
  route('/api/export', 'api/export.ts'),
  route('/health', 'api/health.ts'),
  route('/.well-known/kete', 'well-known/kete.ts'),
  route('/.well-known/oauth-protected-resource', 'well-known/oauth-protected-resource.ts'),
]);
